### ISSUE TITLE
Create Initial Design

### ISSUE THREAD

**Issue by daviddarnes** [daviddarnes/darn.es#1]
- [x] Create wireframe
- [x] Create design based on wireframe
    - [x] Submit to dribbble for feedback?

**Comment by daviddarnes** [comment]
Inspiration:
- http://craigcoles.co.uk/cv
- http://daneden.me/

**Comment by daviddarnes** [comment]
First draft on dribbble https://dribbble.com/shots/2215284-darn-es-Initial-Design

**Comment by craigcoles** [comment]
Aw shucks!

![](http://24.media.tumblr.com/tumblr_m80dp405kM1qlyw8ro1_500.gif)

**Comment by daviddarnes** [comment]
@craigcoles :grin:

**Comment by daviddarnes** [comment]
Feedback review
- Darker type all round
- Try different a font for titles
- Try placing icons between bio and the Portfolio & Blog section
- Mention that I created the Anchor sites in the copy
- Make links more obvious, try orange again for the text

**Comment by daviddarnes** [comment]
Revised design on dribbble https://dribbble.com/shots/2217129-darn-es-Revised-Design

**Comment by daviddarnes** [comment]
Feedback round 2 review
- [ ] Try having each heading the same colour as the icon next to it
- [ ] Try vertically aligning the item content with the centre of the icons
- [ ] Try shrinking the space between [title and content on each item](https://twitter.com/dave_ja/status/637210674838536192)
- [ ] Flip profile pic towards the content

**Comment by daviddarnes** [comment]
Second revision on dribbble https://dribbble.com/shots/2219504-darn-es-Revision-2-Design

**Comment by daviddarnes** [comment]
- [ ] to do
-[x] done

**Comment by daviddarnes** [comment]
Initial design done! Site live at https://darn.es/
