### ISSUE TITLE
License missing from repo

### ISSUE THREAD

**Issue by karan** [daviddarnes/darn.es#7]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by daviddarnes** [comment]
@karan please see https://github.com/daviddarnes/darn.es/issues/3

Considering this is my personal site I kinda don't want anyone copying it, so as you said maybe I shouldn't have a license.
